class GameConfig {
    static maxCameraPlayerSize = 100;
    static minCameraPlayerSize = 48;
    static eaterStartSize = 50;
    static eaterStartMaxSpeed = 10000000;
    static eaterStartSpeedUp = 650;
    static eaterStartSpeedDown = 450;
    static eaterFrictionSpeedDownCoef = 0.008;
    static eaterAccelerateSpeedUp = 3500;
    static eaterAccelerateSpeedLoseSizeCoef = 0.15;
    static eaterSizeTextFont = "Arial";
    static eaterSizeTextFontSizeCoef = 0.5;
    static eaterSizeTextNickNameCoef = 0.3;
    static eaterPointTextSize = new Point(0, 0);
    static eaterPointTextNickName = new Point(0, -25);
    static eaterSizeTextFontColor = "white";
    static eaterCoefSpeedLoseSize = 0.003;//
    static foodSize = 10;
    static foodCost = 2;
    static canvasWidthDefault = 1536;
    static canvasHeghtDefault = 732;
    static gameSceneWidth = 25000;
    static gameSceneHeight = 25000;
    static foodMass = 25000;
    static food2xChance = 0.05;
    static botNumber = 15;
    static botDistAtackEater = 800;
    static botAngry = 10;
    static botAngryAccelerateDistCoef = 0.1;
}